### ISSUE TITLE
Replace the file instead of making a copy

### ISSUE THREAD

**Issue by ShadyMedic** [Dayen0x01/ImagePNG#2]
Would it be possible to add an option to select, whether the user wants to keep the original file or replace it with its `.png` version?

For example, I wanted to convert a few hundreds of images and didn't need to keep the original `JPG`s. I had to delete them all and move the converted `PNG`s into the original folder.

**Comment by Dayen0x01** [comment]
yes bro, thanks for the tip.

this option is already working
